2309/230926/django/hw5_2~4/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

2309/230926/django/hw5_2~4/my_fifth_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

2309/230926/django/hw5_2~4/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

2309/230926/django/hw5_2~4/articles/views.py
from django.shortcuts import render, redirect
from .models import Article


# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    article = Article(title=title, content=content)
    article.save()
    return redirect('articles:index')

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')

2309/230926/django/hw5_2~4/articles/templates/articles/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>게시글이 작성 되었습니다.</h1>
</body>
</html>

2309/230926/django/hw5_2~4/articles/templates/articles/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h2>게시글 상세 페이지</h2>
  <p>게시글 번호 : {{ article.pk }}</p>
  <p>제목 : {{ article.title }}</p>
  <p>생성 시간 : {{ article.created_at }}</p>
  <p>수정 시간 : {{ article.updated_at }}</p>
  <hr>
  <p> {{ article.content }}</p>
  <hr>
  <form action="{% url "articles:delete" article.pk%}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
  <a href="{% url "articles:index" %}">[BACK]</a>
</body>
</html>

2309/230926/django/hw5_2~4/articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>메인 페이지</h1>
  <a href="{% url "articles:new" %}">[CREATE]</a>
  {% for article in articles %}
    <ul>
      <li>{{ article.pk }}번째 글</li>
      <li>제목 : {{ article.title }}</li>
      <a href="{% url "articles:detail" article.pk %}">[DETAIL]</a>
    </ul>
    <hr>
  {% endfor %}
</body>
</html>

2309/230926/django/hw5_2~4/articles/templates/articles/new.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>게시글 생성 페이지</h1>
  <form action="{% url "articles:create" %}" method="POST">
    {% csrf_token %}
    <div>
      <label for="title">제목 : </label>
      <input type="text" id="title" name="title">
    </div>
    <div>
      <label for="content">내용 : </label>
      <textarea name="content" id="content" cols="30" rows="10"></textarea>
    </div>
    <input type="submit" value="CREATE">
  </form>
  <a href="{% url "articles:index" %}">[BACK]</a>
</body>
</html>