2309/230926/django/ws_6_2~3/project2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('travels/', include('travels.urls'))
]

2309/230926/django/ws_6_2~3/travels/urls.py
from django.urls import path
from . import views

app_name = 'travels'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

2309/230926/django/ws_6_2~3/travels/models.py
from django.db import models

# Create your models here.
class Travels(models.Model):
    location = models.CharField(max_length=10)
    plan = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()

2309/230926/django/ws_6_2~3/travels/forms.py
from django import forms
from .models import Travels

class TravelsForm(forms.ModelForm):
    location = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder':'ex) 제주도',
            }
        )
    )
    start_date = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'placeholder':'ex) 2022-02-22',
            }
        )
    )
    end_date = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'placeholder':'ex) 2022-02-22',
            }
        )
    )
    class Meta:
        model = Travels
        fields = '__all__'

2309/230926/django/ws_6_2~3/travels/views.py
from django.shortcuts import render, redirect
from .models import Travels
from .forms import TravelsForm


# Create your views here.
def index(request):
    travels = Travels.objects.all()
    context = {
        'travels':travels,
    }
    return render(request, 'travels/index.html', context)

def create(request):
    # 요청 메서드가 POST라면 (create)
    if request.method == 'POST':
        form = TravelsForm(request.POST)
        # 유효성 검사 진행
        # 유효성 검사가 통과된 경우
        if form.is_valid():
            travel = form.save()
            return redirect('travels:detail', travel.pk)
    # 요청 메서드가 POST가 아니라면 (new)
    else:
        form = TravelsForm()
    context = {
        'form': form,
    }
    return render(request, 'travels/create.html', context)

def detail(request, pk):
    travel = Travels.objects.get(pk=pk)
    context ={
        'travel':travel,
    }
    return render(request, 'travels/detail.html', context)

def delete(request, pk):
    travel = Travels.objects.get(pk=pk)
    travel.delete()
    return redirect('travels:index')

def update(request, pk):
    travel = Travels.objects.get(pk=pk)
    # 요청의 메서드가 POST라면(update)
    if request.method == 'POST':
        form = TravelsForm(request.POST, instance=travel)
        if form.is_valid():
            form.save()
            return redirect('travels:detail', travel.pk)
    # 요청의 메서드가 POST가 아니라면(edit)
    else:
        form = TravelsForm(instance=travel)
    context = {
        'travel': travel,
        'form': form,
    }
    return render(request, 'travels/update.html', context)

2309/230926/django/ws_6_2~3/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <div class="container">
    {% block content %}
    
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

2309/230926/django/ws_6_2~3/travels/templates/travels/create.html
{% extends "base.html" %}
{% block content %}
<h1>CREATE</h1>
<form action="{% url "travels:create" %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="제출">
</form>
<hr>
<a href="{% url "travels:index" %}">[back]</a>
{% endblock content %}

2309/230926/django/ws_6_2~3/travels/templates/travels/detail.html
{% extends "base.html" %}
{% block content %}
<h2>{{ travel.pk }} 번째 여행</h2>
<hr>
<p>장소: {{ travel.location }}</p>
<p>계획: {{ travel.plan }}</p>
<p>시작일: {{ travel.start_date }}</p>
<p>종료일: {{ travel.end_date }}</p>
<hr>
<form action="{% url "travels:delete" travel.pk%}" method="POST">
  {% csrf_token %}
  <input type="submit" value="DELETE">
</form>
<a href="{% url "travels:update" travel.pk%}">[UPDATE]</a>
<hr>
<a href="{% url "travels:index" %}">[back]</a>
{% endblock content %}

2309/230926/django/ws_6_2~3/travels/templates/travels/index.html
{% extends "base.html" %}
{% block content %}
<h1>travels</h1>
<a href="{% url "travels:create" %}">CREATE</a>
<hr>
{% for travel in travels  %}
  <p>장소:{{ travel.location }}</p>
  <p>시작일:{{ travel.start_date }}</p>
  <a href="{% url "travels:detail" travel.pk%}">[detail]</a>
  <hr>
{% endfor %}

{% endblock content %}

2309/230926/django/ws_6_2~3/travels/templates/travels/update.html
{% extends "base.html" %}
{% block content %}
<h1>UPDATE</h1>
<form action="{% url "travels:update" travel.pk%}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="제출">
</form>
<hr>
<a href="{% url "travels:detail" travel.pk%}">[back]</a>
{% endblock content %}