231004/django/ws_9_3/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('<int:pk>/delete',views.delete,name="delete"),
    path('<int:pk>/update',views.update,name="update"),
    path('create/',views.create,name="create"),
    path('<int:pk>/',views.detail,name="detail"),
    path('',views.index,name="index"),
]

231004/django/ws_9_3/movies/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    title = models.CharField(max_length=50)
    director = models.CharField(max_length=30)
    comment = models.TextField()
    

231004/django/ws_9_3/movies/forms.py
from django import forms
from django.forms import widgets
from .models import Movie

class MovieForm(forms.ModelForm):
    title = forms.CharField(
        label="제목",
        widget=forms.TextInput(
            attrs={
                'placeholder':'ex) 세 얼간이',
            }
        ),
    )
    director = forms.CharField(
        label="감독",
        widget=forms.TextInput(
            attrs={
                'placeholder':'ex) 라지쿠마르 히라니',
            }
        ),
    )
    comment = forms.CharField(
        label="코멘트",
        widget=forms.Textarea(
            attrs={
                'placeholder':'ex) 나 얼간이 아니다!',
                'rows': 3,
                'cols': 40,

            }
        )
    )
    
    class Meta:
        model = Movie
        fields = '__all__'

231004/django/ws_9_3/movies/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Movie
from .forms import MovieForm
from django.views.decorators.http import (
    require_POST,
    require_http_methods,
    require_safe,
)
from django.contrib.auth.decorators import login_required

# Create your views here.


@require_safe
def index(request):
    movies = Movie.objects.all()
    context = {"movies": movies}
    return render(request, "movies/index.html", context)


@require_http_methods(["GET", "POST"])
@login_required
def create(request):
    if request.method == "POST":
        form = MovieForm(request.POST)
        if form.is_valid:
            movie = form.save()
            return redirect("movies:detail", movie.pk)
    else:
        form = MovieForm()
    context = {"form": form}
    return render(request, "movies/create.html", context)


@require_safe
def detail(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    context = {
        "movie": movie,
    }
    return render(request, "movies/detail.html", context)


@require_POST
@login_required
def delete(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    movie.delete()
    return redirect("movies:index")


@require_http_methods(["GET", "POST"])
@login_required
def update(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    if request.method == "POST":
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid:
            form.save()
            return redirect("movies:detail", movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        "movie": movie,
        "form": form,
    }
    return render(request, "movies/update.html", context)

231004/django/ws_9_3/movies/templates/movies/create.html
<!-- create.html -->

{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <form action="{% url 'movies:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'movies:index' %}">[back]</a>
{% endblock %}

231004/django/ws_9_3/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <h2>DETAIL</h2>
  <h3>{{ movie.pk }} 번째 글</h3>
  <hr>
    <p>제목 : {{ movie.title }}</p>
    <p>감독 : {{ movie.director }}</p>
    <p>코멘트 : {{ movie.comment }}</p>
  <form action="{% url 'movies:delete' movie.pk%}" method="POST">
    {% csrf_token %}
    <input type="submit" value = "DELETE">
  </form>
  <a href="{% url 'movies:update' movie.pk%}">[UPDATE]</a>
  <hr>
  
  <a href="{% url 'movies:index' %}">[back]</a>
{% endblock  %}

231004/django/ws_9_3/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Movies</h1>
  {% if request.user.is_authenticated %}
    <a href="{% url 'movies:create' %}">[CREATE]</a>
  {% else %}
    <a href="{% url "movies:create" %}">[새 글을 작성하려면 로그인하세요.]</a>
  {% endif %}
  
  <hr>
  {% for movie in movies %}
    <p>제목 : {{ movie.title }}</p>
    <p>감독 : {{ movie.director }}</p>
    <a href="{% url 'movies:detail' movie.pk %}">[detail]</a>
    <hr>
  {% endfor %}
{% endblock %}

231004/django/ws_9_3/movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <form action="{% url 'movies:update' movie.pk%}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'movies:detail' movie.pk%}">[back]</a>
{% endblock %}